services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db  
    image: vpiaskarski/home-library-service
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    volumes:
      - ./:/usr/src/app
      - node-modules:/usr/src/app/node_modules
    networks:
      - db

  db:
    image: vpiaskarski/database
    build:
        context: ./database
        dockerfile: Dockerfile
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  node-modules:

networks:
  db: